# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 065d670dbf20baa7401f81d44c5cb48ba9dc2969afeb1c41d008dd2732dbac4633ec08921b6536a4eeb8d1508392efc6a50a2aed195e011abb9bbf8d6294b59f

test:
  secret_key_base: f13e094ed85c4d08689277efdcc4ee899ecb5e294771a11f9e107a56883f81a1df7253385f92b702ff19baa68d01292171aa5545f42580a3815dcaec315e7b73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
